### ISSUE TITLE
FYI: How to use Node 10

### ISSUE THREAD

**Issue by devth** [martyan/nextbase#1]
I followed the instructions to set this up except I switched to node 10 in `package.json`:

```
  "engines": {
    "node": "10"
  },
```

But when I deployed the web app just 500s with this error:

```
 Error: Cannot find module 'core-js/library/fn/promise'
```

Then I tried switching to node 10 in `src/functions/.babelrc` as well:

```
"node": "10.15.3"
```

This still 500'd. After some further digging I found [this nextjs issue](https://github.com/zeit/next.js/issues/6332).

The fix was:

```
yarn add core-js
```

After that the error went away.

Posting this here for anyone else who wishes to use Node 10 (currently in Beta on Cloud Functions).

**Disclaimer** 

![noidea](https://user-images.githubusercontent.com/86107/63362519-30232680-c32f-11e9-8d42-8ccd50e99c2c.gif)

**Comment by martyan** [comment]
Thanks a lot for the details of implementation with Node 10. I will check it in next few days and update the readme accordingly.

**Comment by martyan** [comment]
It has been long waiting but the support for Node 10 should be no problem.
Nextbase is using Node 12 as engine now.
